### ISSUE TITLE
Installed plugins will not upgrade

### ISSUE THREAD

**Issue by schisamo** [sous-chefs/jenkins#122]
Issue originally reported by Tucker on the Chef mailing list:
http://lists.opscode.com/sympa/arc/chef/2014-01/msg00221.html

```
I'm also seeing plugins not upgrading when a version is specified:

[2014-01-15T12:57:02-05:00] INFO: Processing jenkins_plugin[ldap] action install (jenkins-cookbook::master line 56)
[2014-01-15T12:57:02-05:00] DEBUG: Load jenkins_plugin[ldap] plugin information from /srv/jenkins/plugins/ldap/META-INF/MANIFEST.MF
[2014-01-15T12:57:02-05:00] DEBUG: jenkins_plugin[ldap] already installed - skipping

The ldap plugin is still 1.2 and not 1.7, as specified.  I'll look at this deeper in a bit but felt it was worth mentioning.
```

Issue reported on Jenkins 1.532-1.1 installed from packages on CentOS.

**Comment by jkburges** [comment]
FWIW, I found 'pinning' the bundled plugin which you want to upgrade works:

```ruby
file "<JENKINS_HOME>/plugins/<plugin_name>.jpi.pinned") do
  mode   '0644'
  owner  node['jenkins']['master']['user']
  group  node['jenkins']['master']['group']
  action :touch
end

jenkins_plugin <plugin_name>
```

This has the advantage of using the `jenkins_plugin` resource, which in turn enables a particular version to be installed, whereas @neovatar's solution always get the latest (probably ok for people).

**Comment by gtirloni** [comment]
I found this thread because I was having the same issue with old bundled plugins getting reinstalled, even though I had downloaded newer version. The only solution that worked was to pin them. It seems that, as Jenkins works to unbundle more functionality as plugins, this situation should disappear or get better in the future. Thank you!

**Comment by ndobson** [comment]
@jkburges thanks that works great.

**Comment by lioramilbaum** [comment]
The code snipped presented by @neovatar is no longer working.  The attribute node['jenkins']['master']['pluginlist'] is missing. Any idea how to make it work?

**Comment by zorancco** [comment]
I couldn't find the attribute referenced in the @neovatar's script either so I dug into the attributes and found the 
node['jenkins-server']['plugins']

and then got the following script to work:
`# execute list-plugins to make sure cli is available
jenkins_command 'list-plugins'

# get jenkins plugin updates
execute 'get-update-json' do
  command "curl -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- #{node['jenkins']['master']['endpoint']}/updateCenter/byId/default/postBack"
  action :run
end

# install jenkins plugins
node['jenkins-server']['plugins'].each do |plugin_name, plugin_params|
  jenkins_command "install-plugin #{plugin_name}"
end

# restart jenkins via cli to ensure plugins are active
jenkins_command 'safe-restart'

# execute list-plugins to make sure cli is available
jenkins_command 'list-plugins'`

and using the jenkins_plugin resource you should be able to simply replace all of the above with:

`node['jenkins-server']['plugins'].each do |plugin_name, plugin_params|
  jenkins_plugin plugin_name do
    version plugin_params.version
  end
end`
