### ISSUE TITLE
Slave setup steps

### ISSUE THREAD

**Issue by abhinavn** [sous-chefs/jenkins#144]
Hi

I created master and now I am trying to create slaves for jenkins using this cookbook. However I don't see slave recipe. How does slave creation work?

I bootstrapped VM with chef-client and uplaoded jenkins cookbook to my chef-server. How do I tell chef that VM is supposed to be a slave?

Thanks

P.S - I am new to Chef and just started working on it today, pardon my ignorance

**Comment by vikas6393** [comment]
can i know how you converted as slave machine, u mean using launch slave agents via ssh?
