### ISSUE TITLE
jenkins_private_key_credentials gives error 'Neither PUB key nor PRIV key:: nested asn1 error'

### ISSUE THREAD

**Issue by clementbethuys** [sous-chefs/jenkins#148]
Hi,

I think there is a problem with jenkins_private_key_credentials for cookbook version "2.0.2" (the only I tested)

when using:

``` ruby
jenkins_private_key_credentials cred do
    description cred
    private_key "-----BEGIN RSA PRIVATE KEY-----\nMIIEpgIBAAKC ..."
end
```

got this error

``` bash
OpenSSL::PKey::RSAError
-----------------------
Neither PUB key nor PRIV key:: nested asn1 error
```

with this details

``` bash
/var/chef/cache/cookbooks/jenkins/libraries/credentials_private_key.rb:

 40:      # @param [String] arg
 41:      # @return [String]
 42:      #
 43:      def private_key(arg = nil)
 44:        if arg.nil?
 45:          @private_key
 46:        else
 47>>         arg = OpenSSL::PKey::RSA.new(arg).to_pem unless arg.empty?
 48:          set_or_return(:private_key, arg, kind_of: String)
 49:        end
 50:      end
 51:
 52:      #
 53:      # Passphrase for the private key of the credentials.
 54:      #
 55:      # @param [String] arg
 56:      # @return [String]
```

I'am using the omnibus chef-client

``` bash
Chef: 11.8.2
```

Is this a bug or a kind of formating issue ? 
Thanx in advance

**Comment by CharlesTBetz** [comment]
As a newcomer to some of these issues, the interesting learning here for me was that the RSA key *requires* newlines - they cannot be removed. I thought that directly concatenating the main body of the key was acceptable, e.g.:

     private_key "-----BEGIN RSA PRIVATE KEY-----\n"+ 
    "MIIEpgIBAAKCAQEAonaSkhxhTZHWa2uIjbqg9L/WtWyZh4he25AsBnGGKVWxWP07"+
    "AX5oekShQRg/X1oIoTFOmdfA3rHbSvaadCZT5UKz4gDaF+tw+c6jrMBoW7mEnxLc"+

But that results in the "Neither PUB key nor PRIV key: nested asn1" error. Your key apparently must be concatenated with newlines:

     private_key "-----BEGIN RSA PRIVATE KEY-----\n"+ 
    "MIIEpgIBAAKCAQEAonaSkhxhTZHWa2uIjbqg9L/WtWyZh4he25AsBnGGKVWxWP07\n"+
    "AX5oekShQRg/X1oIoTFOmdfA3rHbSvaadCZT5UKz4gDaF+tw+c6jrMBoW7mEnxLc\n"+

At least that was how I got past this error. 

I will be following the best practice recommendation to put the key in an encrypted data bag, but wanted to exercise the API first by putting a dummy private key directly in the code. Hopefully this will be of use if someone else follows the same thought process.

**Comment by mromero-convoso** [comment]
Creating a key with the following `ssh-keygen` command is what worked for me:
```
ssh-keygen -m PEM -t rsa -b 4096
```
