### ISSUE TITLE
Jenkins CI apt and yum repos only provides current versions

### ISSUE THREAD

**Issue by erichelgeson** [sous-chefs/jenkins#170]
Platform Ubuntu 12.04.2 & Centos 6.4

Setting `default['jenkins']['master']['version'] = "1.555"`

I get:
`E: Version '1.555' for 'jenkins' was not found`

It looks as though Jenkins only shows the current version in their apt repo:

```
$ apt-cache madison jenkins
   jenkins |      1.557 | http://pkg.jenkins-ci.org/debian/ binary/ Packages
   jenkins | 1.424.6+dfsg-1ubuntu0.2 | http://us.archive.ubuntu.com/ubuntu/ precise-updates/universe amd64 Packages
   jenkins | 1.424.6+dfsg-1ubuntu0.1 | http://security.ubuntu.com/ubuntu/ precise-security/universe amd64 Packages
etc..
```

This seems most likely an issue that Jenkins doesn't provide anything besides `current` in the apt repo (and effectively makes package installation unusable as `1.556/7` have a bug with ssh key auth)

I guess I'm opening this bug more for visibility and maybe warn that version and packages cant be used together or am I completely missing something.

**Comment by thiagofigueiro** [comment]
This is now a bit of a thorn because Jenkins 2.0 was released and it breaks compatibility with 1.x. Specifically for me, `jenkins_plugin 'backup'` doesn't work anymore.

**Comment by NitinMahajan23** [comment]
superb
