### ISSUE TITLE
Setting Encrypted Values for AD Auth Plugin

### ISSUE THREAD

**Issue by nagash77** [sous-chefs/jenkins#199]
I am currently trying to create a cookbook that deploys a fully configured jenkins server.  We currently use AD integration to lock down our server.  I have the cookbook getting the server up and working and installing the plugin for AD auth.  I am currently writing out the /var/lib/config.xml which is properly setting the values for every field except Bind Password.  This value is stored encrypted in config.xml.  I have tried copying the secret.key and identity.key over during the build out of the box.  It writes out the same string I would expect, except when I go into the interface the field is crazy long and doesnt work.  If i put in the correct password and save the config, the value in the jenkins config.xml file is different!  Wondering if you had any advise as to how to get this setting into my build?

**Comment by buzyd2000** [comment]
this answer did not provide the answer to the question

**Comment by bby-bishopclark** [comment]
isn't using non-idempotent non-whyrun-compliant tools an anti-pattern as well?
