### ISSUE TITLE
Error executing 'create' on resource 'jenkins_private_key_credentials'

### ISSUE THREAD

**Issue by dvlscm** [sous-chefs/jenkins#236]
My cookbook uses the following resource:

``` ruby
jenkins_private_key_credentials 'jenkins' do
  description "jenkins"
  private_key ...
  action :create
end
```

When I run it, I get the following error:

```
=======================================================================
Error executing action `create` on resource 'jenkins_private_key_credentials[jenkins]'
=======================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '255'
---- Begin output of java -jar /var/chef/cache/jenkins-cli.jar -s http://localhost:8080 groovy /tmp/groovy20140630-8077-1u9okr2 ----
STDOUT: 
STDERR: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
RemoteClass: 47: unexpected char: '#' @ line 47, column 11.
             #<Chef::DelayedEvaluator:0x00000002a31950@/home/ubuntu/chef-solo/cookbooks-2/jenkins/libraries/credentials.rb:47>,
             ^

1 error

    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:302)
    at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:149)
    at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:119)
    at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:131)
...
```

This looks like a compile error deep inside the jenkins cookbook. Is this clearly user error on my part in some way, or is there an issue beyond my ability to solve via configuration?

My Berksfile.lock shows that I'm using v2.1.0 of the cookbook.

**Comment by okram999** [comment]
Good question, this was in my mind for sometime now. "When a fix like this goes in, do I have to do anything special to get it, or do I get it automagically the next time I run chef-solo and re-vendor my cookbooks?"  My setup is - i have the entry as " cookbook 'jenkins'" in the Berksfile & the recipe have the declaration, " include_recipe 'jenkins::master'. 

This may be like asking how to cut a fruit in the fruit-juice factory, but will definitely help start-ups :)

@sethvargo
