### ISSUE TITLE
hudson.security.accessDeniedException2: anonymous is missing the Overall/RunScripts permission

### ISSUE THREAD

**Issue by dvlscm** [sous-chefs/jenkins#263]
I get that exception when using this resource:

``` ruby
jenkins_private_key_credentials 'jenkins' do
  description "jenkins"
  private_key my_private_key
  action :create
end
```

I'm using GitHub Committer Authorization Strategy for Jenkins, not Matrix Security. The latter lets me specify the permissions for Anonymous, but the former doesn't. I've checked these options for the jenkins user:
- Grant READ permissions for /github-webhook
- Grant READ permissions for Anonymous Users

Those apparently make no difference. My GitHub webhook works, and the users are working fine. It also looks like the Jenkins cookbook creates the private key credential (at least it shows up in the credentials for the jenkins user in the Credentials plugin).

Any idea how to get rid of this exception when I'm using GitHub Committer Authorization Strategy?

**Comment by Brantone** [comment]
Should this ticket be re-opened due to:
https://jenkins.io/security/advisory/2017-04-10/#matrix-authorization-strategy-plugin-allowed-configuring-dangerous-permissions
?
