### ISSUE TITLE
jenkins_jnlp_slave resource is not compatible with OS X

### ISSUE THREAD

**Issue by notnmeyer** [sous-chefs/jenkins#456]
I'm setting up a build slave on OS X. The `jenkins_jnlp_slave` resource [insists on configuring a runit service](https://github.com/chef-cookbooks/jenkins/blob/master/libraries/slave_jnlp.rb#L227-L248), but [Heavy Water's runit cookbook](https://github.com/hw-cookbooks/runit) doesn't support OS X. I'm not finding a list supported platforms for this cookbook so not sure if OS X support is even expected here. The way this is written, it's extremely difficult to modify the resource at runtime and :nothing the runit_service's action. Would be great if the runit support was optional, or easier to "rewind" when necessary.

It'll fail like this on OS X:

```
  Errno::ENOENT
           -------------
           runit_service[jenkins-slave] (dynamically defined) had an error: Errno::ENOENT: link[/etc/init.d/jenkins-slave] (/tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb line 246) had an error: Errno::ENOENT: No such file or directory @ sys_fail2 - (/usr/bin/sv, /etc/init.d/jenkins-slave)
```

There are a couple issues here, the first is that since there's no runit support in the upstream cookbook, runit is never installed (but is available via homebrew). The second is assuming `/etc/init.d` exists.

**Comment by petewilcock** [comment]
I am also encountering this issue with a OS X slave. Did you ever find a workaround? I've installed runit but that doesn't appear to help.

**Comment by notnmeyer** [comment]
the upstream runit cookbook doesnt support os x, and despite a couple mentions of os x in this cookbook, there's not complete support. what is necessary here is removing the runit bits (at least for os x) and using launchd or something. 

but really, starting a JNLP slave is as simple as grabbing the slave.jar and running it on the slave as described [here](https://wiki.jenkins-ci.org/display/JENKINS/Distributed+builds). so the path of least resistance might just be to roll your own recipe that handles that.

**Comment by iennae** [comment]
Hey folks,

Just want to acknowledge that we recognize that by including runit as a dependency that causes some lock-in. We do plan to refactor this, it's just not at the top of the stack right this minute. We'll keep you updated on the progress to do this. Thanks for your patience!

**Comment by iennae** [comment]
(If someone does have a working recipe they've written to do this with accompanying tests, I'm happy to pull that into the cookbook!)
