### ISSUE TITLE
JNLP slave to a windows machine errors out on remote_fs file location

### ISSUE THREAD

**Issue by joshoohaah** [sous-chefs/jenkins#480]
### Cookbook version

2.5.0
### Chef-client version

12.10.24
### Platform Details

Centos 6.7 
### Scenario:

Issue creating windows JNLP slave using LWRP.  when a windows jnlp slave is made and pointing to `remote_fs "C:/jenkins"` .  The LWRP errors out and cannot handle the windows style folder structure, and gives the following error.  `STDERR: usermod: invalid field 'C:/jenkins'`
### Steps to Reproduce:

```
           jenkins_jnlp_slave("WinBuild") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "muse_build_server"
             recipe_name "deploy_slaves"
             description "Windows Build server"
             remote_fs "C:/jenkins"
             executors 4
             usage_mode "normal"
             availability "always"
             labels ["builder", "linux"]
             user "jenkins-builder"
             group "jenkins-builder"
             slave_name "WinBuild"
           end
```
### Expected Result:

a JNLP slave would be created and remote_fs would point to `C:/jenkins`
### Actual Result:

link to the test-kitchen output in a gist for the error: https://gist.github.com/joshoohaah/1dc7f53c40bf5e7b8d6fbbaedc479594

**Comment by docwhat** [comment]
According to the instructions, the `jenkins_jnlp_slave` resource should be run on the *slave* not the *master*.  Unlike the `jenkins_ssh_slave` resource.

**Comment by joshoohaah** [comment]
Well look at that.  I bow :bow: to you @docwhat .  I'll use my glasses better next time

**Comment by damacus** [comment]
Closing this issue as stale. It was opened in 2016 and the cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.
