### ISSUE TITLE
cookbook doens't work with runit 2.0

### ISSUE THREAD

**Issue by jsyrjala** [sous-chefs/jenkins#506]
Latest version of the jenkins cookbook has this in metadata.

```
 depends 'runit', '~> 1.7'
```

Updating jenkins cookbook `knife cookbook site install jenkins -z` to my local repository caused also runit to get updated to latest version. runit 2.0 got released yesterday, so above command updates runit to version 2.0.

The end result is that jenkins cookbook doesn't find a correct version of runit (runit 2.0 doesn't match '~> 1.7´) and refuses to install.

I am using Amazon OpsWorks.

**Comment by zepheiryan** [comment]
The 2.6.0 release also depends on yum `~> 3` while yum 4.0.0 is out.  If you end up needing the jenkins cookbook and later versions of yum and/or runit cookbooks, the dependency solver may resort to Jenkins cookbook version 1.2.2 to satisfy all version restrictions.

**Comment by tas50** [comment]
This has been fixed in master
