### ISSUE TITLE
On a clean checkout after gem install; rake fails due to 'kitchen/rake_tasks' missing

### ISSUE THREAD

**Issue by mehmetg** [sous-chefs/jenkins#544]
### Cookbook versionb
branch: master

### Chef-client version
N/A

### Platform Details
MacOS 10.12.1

### Scenario:
Attempting to run tests on a clean checkout, but rake fails.

### Steps to Reproduce:
* clone repo
* run: `bundle install`
* run: `rake -T`

### Expected Result:
No errors and a list of rake tasks available.

### Actual Result:
The following error shows up:
`LoadError: cannot load such file -- kitchen/rake_tasks
/Users/mehmetgerceker/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/mehmetgerceker/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/mehmetgerceker/workspace/chefWorkspace/jenkins/Rakefile:48:in `block in <top (required)>'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task_manager.rb:205:in `in_namespace'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/dsl_definition.rb:140:in `namespace'
/Users/mehmetgerceker/workspace/chefWorkspace/jenkins/Rakefile:46:in `<top (required)>'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Users/mehmetgerceker/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/mehmetgerceker/.rvm/rubies/ruby-2.3.1/bin/rake:23:in `load'
/Users/mehmetgerceker/.rvm/rubies/ruby-2.3.1/bin/rake:23:in `<main>'
`

**Comment by cheeseplus** [comment]
This has been resolved and we also now use `delivery local` for testing in TravisCI and in preference over a Rakefile
