### ISSUE TITLE
private key authentication not falling back to anonymous

### ISSUE THREAD

**Issue by coltrey** [sous-chefs/jenkins#609]
My jenkins install workflow is basically like this:
set node.run_state[:jenkins_private_key]
install openjdk8 & set default
include jenkins_master
install plugins
jenkins_command safe-restart
use templates for config.xml and other (including authentication with saml-plugin)
jenkins_command safe-restart
setup jobs
jenkins_command safe-restart

The above workflow works great with jenkins 2.44 and cookbook version 4.2.1
Trying to update to Jenkins 2.59 and it fails - can't authenticate for the first plugin install on fresh hardware. The error is java.security.GeneralSecurityException: Authentication failed. No private key accepted.

I looked at [_exector.rb ](https://github.com/chef-cookbooks/jenkins/blob/master/libraries/_executor.rb) and it looks like the behavior is supposed to fall back to an anonymous request for that kind of error, but the regex may be wrong:

lines 101-103:
```
        if ((exitstatus == 255) && (stderr =~ /^Authentication failed\. No private key accepted\.$/)) ||
           ((exitstatus == 255) && (stderr =~ /^java\.io\.EOFException/)) ||
           ((exitstatus == 1) && (stderr =~ /^Exception in thread "main" java\.io\.EOFException/))

```

If I move setting node.run_state[:jenkins_private_key] to after the plugins, the error is "anonymous doesn't have overall read permission" - so it seems like the credential is cached or something - but really, the steps above should fall back to unauthenticated rather than having to do this.

### Cookbook version
5.0.1

### Chef-client version
Chef: 12.7.2

### Platform Details
AWS Linux

### Scenario:
install plugins before setting up authentication and handle jenkins_command executions after authentication is setup

### Steps to Reproduce:
set node.run_state[:jenkins_private_key]
jenkins_plugin <plugin>
FAIL

### Expected Result:
plugins installed

### Actual Result:
```
================================================================================[0m
[31mError executing action `install` on resource 'jenkins_plugin[ace-editor]'[0m
================================================================================[0m

[0mMixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '255'
[0m---- Begin output of "java" -jar "/var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" -i "/var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/jenkins-key" install-plugin /var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/ace-editor-1.1.plugin -name ace-editor  ----
[0mSTDOUT: 
[0mSTDERR: May 10, 2017 4:37:01 PM hudson.cli.CLI _main
[0mWARNING: null
[0mjava.security.GeneralSecurityException: Authentication failed. No private key accepted.
[0m	at hudson.cli.CLI.authenticate(CLI.java:758)
[0m	at hudson.cli.CLI._main(CLI.java:598)
[0m	at hudson.cli.CLI.main(CLI.java:407)
[0m---- End output of "java" -jar "/var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" -i "/var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/jenkins-key" install-plugin /var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/ace-editor-1.1.plugin -name ace-editor  ----
[0mRan "java" -jar "/var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" -i "/var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/jenkins-key" install-plugin /var/chef/runs/3cf2beaf-b766-4840-aede-f61f6b92700d/local-mode-cache/cache/ace-editor-1.1.plugin -name ace-editor  returned 255[0m


```

**Comment by crerwin** [comment]
I'm hitting this issue too with both Jenkins 2.46.2 and 2.59/2.60.  I can confirm that the change in the PR fixes it for me.

**Comment by coltrey** [comment]
What do I need to do to get this merged?

**Comment by dshvedchenko** [comment]
Hi, have similar PR https://github.com/chef-cookbooks/jenkins/pull/607

Your one blocked because commit is not signed
