### ISSUE TITLE
Cannot disable master Jenkins node

### ISSUE THREAD

**Issue by Poohblah** [sous-chefs/jenkins#616]
In our org, we are running a Jenkins cluster where jobs run exclusively on the executor nodes and the master node just runs the web interface and schedules jobs on the executors.  We are trying to Chef-ify this setup.  However, there doesn't appear to be any supported way of disabling the master node.  Here's what I've tried so far:

----

```
jenkins_slave 'master' do
  action :offline
end
```
Result: nothing appears to change. Jobs can still be scheduled on the master node.

----

```
jenkins_slave 'master' do
  action :delete
end
```
Result: nothing appears to change. The master node still appears in the nodes list and jobs can still be scheduled on it.

----

```
jenkins_slave 'master' do
  action :disconnect
end
```
Result: nothing appears to change.  The master node is still online and jobs can still be scheduled on it.

----

```
jenkins_slave 'master' do
  executors 0
end
```
Result:

```
================================================================================
Error executing action `create` on resource 'jenkins_slave[master]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "/usr/lib/jvm/java/bin/java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" -i "/tmp/kitchen/cache/jenkins-key" groovy /tmp/groovy20170516-18605-6b9iac ----
STDOUT: 
STDERR: ERROR: Unexpected exception occurred while performing groovy command.
hudson.model.Descriptor$FormException: Invalid agent configuration for master. Invalid # of executors.
        at hudson.model.Slave.<init>(Slave.java:206)
        at hudson.model.Slave.<init>(Slave.java:155)
        at hudson.slaves.DumbSlave.<init>(DumbSlave.java:60)
        [rest of stack trace snipped]

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/jenkins/libraries/_executor.rb:87:in `execute!' 
/tmp/kitchen/cache/cookbooks/jenkins/libraries/_executor.rb:140:in `groovy!'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/slave.rb:158:in `block in do_create'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/slave.rb:157:in `do_create'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/slave.rb:150:in `block in <class:JenkinsSlave>'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/cub_policy_sis_jenkins_master/recipes/default.rb

 11: jenkins_slave 'master' do
 12:   executors 0
 13: end
 14: 

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/cub_policy_sis_jenkins_master/recipes/default.rb:11:in `from_file'

jenkins_slave("master") do
  action [:create]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :jenkins_slave
  cookbook_name "cub_policy_sis_jenkins_master"
  recipe_name "default"
  executors 0
  slave_name "master"
  usage_mode "normal"
  description "Jenkins slave master"
  remote_fs "/home/jenkins"
end
```

----

```
jenkins_slave 'master' do
  usage_mode 'exclusive'
end
```
Result: a new slave is created called "master" which appears separately from the real master node in the nodes list.

**Comment by Poohblah** [comment]
The following workaround seems to do the trick:

```
# resources/master_node.rb

property :config_path, String, default: '/var/lib/jenkins/config.xml'
property :executors, Integer, default: 2
property :executors_xpath, String, default: '//numExecutors'
property :name, String, name_property: true

load_current_value do
  require 'nokogiri'
  xml = Nokogiri::XML(::File.open(config_path))
  executors xml.at_xpath(executors_xpath).content.to_i
end

action :update do
  converge_if_changed do
    require 'nokogiri'
    xml = Nokogiri::XML(::File.open(config_path))
    xml.at_xpath(executors_xpath).content = executors
    ::File.open(config_path, 'w') { |f| f.write(xml.to_xml) }
  end
end
```

```
# recipes/default.rb

my_cookbook_master_node 'master' do
  executors 0
  notifies :restart, 'service[jenkins]', :delayed
end
```

**Comment by espoelstra** [comment]
@Poohblah It is possible to set the number of executors to 0 or you can set the master to "EXCLUSIVE" mode aka only specific labels will run on it (which can be useful for "flyweight" jobs that don't actually require resources and are just for tracking the state of a set of downstream jobs). In our case we use Groovy to call the methods rather than hacking at the config.xml with Ruby, this is much safer and you get warnings if you call the wrong method or use an incorrect/invalid value.

If you would like an example ping me and I'll see about digging it out of our code.

**Comment by Poohblah** [comment]
@espoelstra thanks.  When I created this issue a year ago, I was new to Jenkins and unfamiliar with its Groovy/Java API.  Now I am much more familiar with it and I have learned that the master node can be easily disabled with a one-liner Groovy script:

```
Jenkins.instance.setNumExecutors(0)
```

I just happen to come from Unix/Linux administration land where almost everything is configured via text files and not APIs, so that was the approach I was most familiar with :)
