### ISSUE TITLE
jenkins_jvm_options not setting on Amazon Linux

### ISSUE THREAD

**Issue by tdigangi5** [sous-chefs/jenkins#626]
### Cookbook version
5.0.1

### Chef-client version
12.19.36

### Platform Details
amazon linux

### Scenario:
On the install of jenkins::master via test-kitchen. I can not get jenkins_jvm_options to be set in the _/etc/sysconfig/jenkins_ file.

It appears that this functionality should work https://github.com/chef-cookbooks/jenkins/blob/0aef5dd183a0e12ea31617404880cf946a87af68/templates/default/jenkins-config-rhel.erb

JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true"
<% if node['jenkins']['master']['jvm_options'] %>
JENKINS_JAVA_OPTIONS="$JENKINS_JAVA_OPTIONS <%= node['jenkins']['master']['jvm_options'] %>"
<% end %>

however it is not working on this flavor of linux

### Steps to Reproduce:
1. Add `include_recipe "jenkins::master"` to _recipes/default.rb_ in cookbook wrapper
2. Add `node.normal['jenkins']['master']['jvm_options'] = '-Djenkins.install.runSetupWizard=false'` to attributes to _attributes/default.rb_
3. `kitchen converge`

### Expected Result:
After install
_/etc/sysconfig/jenkins_ file contains
`JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
`
### Actual Result:
After install
/etc/sysconfig/jenkins file contains
JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true"

**Comment by tas50** [comment]
At the moment we don't support Amazon Linux, but it's a platform we'd like to tackle once we get the Ubuntu/RHEL support where it needs to be.

**Comment by tdigangi5** [comment]
Can you confirm the setup I am using should work and this feature is functional on supported Linux versions?
