### ISSUE TITLE
Request to remove runit

### ISSUE THREAD

**Issue by fgs-dbudwin** [sous-chefs/jenkins#628]
### Cookbook version
5.0.2

### Chef-client version
Chef Development Kit Version: 1.4.3
chef-client version: 12.19.36
delivery version: master (41b94ffb5efd33723cf72a89bf4d273c8151c9dc)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1

### Platform Details
Windows 10, converging a Centos 7.3.1611 node

### Scenario:
Converge works the first time, but subsequent converges fail when trying to install plugins because the Jenkins service isn't started.  The only solution is to `kitchen destroy` and `kitchen converge` after making any change.

### Steps to Reproduce:
Using the Jenkins WAR file and a list of plugins.  `kitchen converge` the first time will be successful, immediately running `kitchen converge` a second, third, forth time will fail because the Jenkins service isn't running.

### Expected Result:
Jenkins to behave like it did after the first `kitchen converge`.

### Actual Result:
Error during `kitchen converge` because the Jenkins service isn't running.

Runit has not been updated in almost 3 years.  We were able to confirm that the issue I am having is not a direct issue with this cookbook, but a bug in runit.  When I do a `kitchen converge` for the first time successfully, then do a `kitchen login`, if I then manually stop the service and then try to manually restart it, runit still says that Jenkins is down.  This is effectively the same thing I noticed when I do a converge subsequent times.  The cookbook rightly tells runit to start again, but runit fails to start the service.  I am running a clean install of Centos 7.3.1611 when I try this.  I would like to see this cookbook remove the runit dependency and rely on the default init system.  Other cookbooks have gone this route lately, like [the version 6.0.0 of the nginx_chef cookbook](https://github.com/chef-cookbooks/chef_nginx/blob/578cfeb25237a672ea6bbe261fca89281195a27c/CHANGELOG.md) released this spring.

**Comment by tas50** [comment]
It's time and I'd love to do it. We need to make sure we fully support Upstart/Systemd/Sys-V so we can continue to support RHEL 6+, Debian 7+, and Ubuntu 14.04+. We also have to make sure we cleanup the old runit configs so we don't end up with double processes running. It's tricky, but totally worth it.

**Comment by fgs-dbudwin** [comment]
I made an [earnest attempt to remove runit in an open pull request](https://github.com/chef-cookbooks/jenkins/pull/629), hopefully that can be a building block for the community to get this done!

**Comment by tas50** [comment]
We'll have to build out a jenkins_service resource that can abstract away the different service types (systemd/upstart/sys-v). We have a few examples floating around. I'm sticking this on our project board as removing runit in all our cookbooks was something we identified for 2017.

**Comment by bby-bishopclark** [comment]
Please ensure support for other service types isn't later removed once built.  We're plotting our post-systemd strategy (more a weaning) well in advance, and would hate to see this cookbook lose versatility.

**Comment by tas50** [comment]
This cookbook, like others, will support native init systems. For the most part now that just means systemd.
