### ISSUE TITLE
When changing the jenkins home, stop running service first

### ISSUE THREAD

**Issue by thedrewster-u51** [sous-chefs/jenkins#656]
### Cookbook version
jenkins-5.0.4

### Chef-client version
Chef: 13.3.42

### Platform Details
Ubuntu 14.04 (Very likely applicable to all *nix OS'es)

### Scenario:
When you try to change the attribute ['jenkins']['master']['home'] to another location on an already installed / running jenkins server, the chef run will fail because a "usermod -d" is performed.  This will fail, since the jenkins server is already running

### Steps to Reproduce:
Run jenkins recipe once without altering the ['jenkins']['master']['home'] attribute. Then change ['jenkins']['master']['home'] to an alternate location and run the recipe again.

### Expected Result:
If jenkins is already running, and the user home directory is changed, stop the service first.

### Actual Result:
```           ================================================================================
           Error executing action `create` on resource 'linux_user[jenkins]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '8'
           ---- Begin output of ["usermod", "-d", "/jenkins", "jenkins"] ----
           STDOUT:
           STDERR: usermod: user jenkins is currently used by process 12553
           ---- End output of ["usermod", "-d", "/jenkins", "jenkins"] ----
           Ran ["usermod", "-d", "/jenkins", "jenkins"] returned 8

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/jenkins/recipes/_master_war.rb

            28: user node['jenkins']['master']['user'] do
            29:   home node['jenkins']['master']['home']
            30:   system node['jenkins']['master']['use_system_accounts'] # ~FC048
            31: end
            32:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jenkins/recipes/_master_war.rb:28:in `from_file'

           linux_user("jenkins") do
             action [:create]
             default_guard_interpreter :default
             username "jenkins"
             uid nil
             gid nil
             home "/jenkins"
             system true
             iterations 27855
             declared_type :user
             cookbook_name "jenkins"
             recipe_name "_master_war"
           end

           System Info:
           ------------
           chef_version=13.3.42
           platform=ubuntu
           platform_version=14.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=13840;start=09:43:14;
```
### Workaround
Manually stop the jenkins server first before running the recipe.

**Comment by iennae** [comment]
Thanks for reporting this issue. The problem is that while this seems like a very straightforward fix of just stopping the service, it's not. Changing that attribute changes a major state of the system. It's not expected to be changed via a Chef run. In all likelihood this could cause a lot of problems where the system gets into a split brain state of having content in different places. If you wanted to change the location of how the system was set up you would need to carefully fix that prior to updating your chef run. Most likely you would want to set up a fresh system and migrate over any data/content that you would want to retain.

**Comment by damacus** [comment]
Closing this issue as stale. It was opened in 2018 and the cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.
