### ISSUE TITLE
Permission denied when installing plugins

### ISSUE THREAD

**Issue by kryptek** [sous-chefs/jenkins#659]
### Cookbook version
5.0.4

### Chef-client version
13.5.3

### Platform Details
Oracle Linux 7

### Scenario:
```ruby
  jenkins_plugin 'credentials' do
    notifies :execute, 'jenkins_command[safe-restart]', :immediately
  end
```

### Steps to Reproduce:
Downloaded the latest cookbook using `knife cookbook site download jenkins`, added to my Berksfile, installed dependencies, used `knife solo cook user@ip` to kick off my run.

### Expected Result:
It should have installed the plugin

### Actual Result:
https://gist.github.com/kryptek/0b9ff5d8ed1074646736f61af3d744ed

I do see that the local-mode-cache is owned by root and I suspect this is why I'm getting the permission denied but I have no idea where to go from here. Any help?

**Comment by kryptek** [comment]
After digging into the issue a bit more I see that this is related to the permissions of the Jenkins server itself. What's the best way to go about getting a default admin user in with the base installation so that I can spring up the server with the plugins I need?

**Comment by jezdikm** [comment]
I have the same problem.
**Cookbook version:** 5.0.4
**Chef-client:** 12.11.18
**Platform:** CentOS 6.9

I am running _chef-client_ in a zero mode (`-z`) as _root_. The _jenkins_plugin[XXX] action install_ fails with:
```
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "java" -jar "/root/.chef/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 -"remoting" -i "/root/.chef/local-mode-cache/cache/jenkins-key" install-plugin file:///root/.chef/local-mode-cache/cache/ace-editor-1.1.plugin -name ace-editor  ----
    STDOUT: Installing a plugin from file:/root/.chef/local-mode-cache/cache/ace-editor-1.1.plugin
    STDERR: ERROR: Unexpected exception occurred while performing install-plugin command.
    java.io.FileNotFoundException: /root/.chef/local-mode-cache/cache/ace-editor-1.1.plugin (Permission denied)
    	at java.io.FileInputStream.open0(Native Method)
...<snip>...
```

The file _/root/.chef/local-mode-cache/cache/ace-editor-1.1.plugin_ exists and has **jenkins** set as owner:group.

I think the problem is in the **executor.execute** on line 319 of _libraries/plugin.rb_. Does it run as Jenkins user? If so it won't be able to read files under /root

**My workaround**: Set _cache_path_ to another location in _/etc/chef/client.rb_

**Comment by DennyZhang** [comment]
@jezdikm 

Yes, I run into the same problem.

Changing cache_path works.

Have you found a more elegant solution, instead of this workaround?

**Comment by jezdikm** [comment]
Unfortunately I have not. Keeping eye on this thread if someone comes up with a better solution of fix.

**Comment by espoelstra** [comment]
You could try setting a user in the run_state, see https://github.com/osuosl-cookbooks/osl-jenkins/blob/master/recipes/powerci.rb#L215

Or another example with an SSH key instead.

https://pghalliday.com/jenkins/groovy/sonar/chef/configuration/management/2014/09/21/some-useful-jenkins-groovy-scripts.html#appendix
