### ISSUE TITLE
jenkins service `start/enable` does not necessarily mean jenkins app is `ready`

### ISSUE THREAD

**Issue by joshoohaah** [sous-chefs/jenkins#664]
### Cookbook version
Jenkins 5.0.5

### Chef-client version
[12.8.x]

### Platform Details
[Centos 7 in AWS]

### Scenario:
When you just install jenkins or chef `service` resource starts/restarts jenkins...when you go onto the next steps jenkins is not always 'ready'.  Some commands that fail then after you restart jenkins would be installing plugins, using `jenkins_command` for safe-restart..etc

### Steps to Reproduce:
   1. create a service resource block to restart jenkins service
   1. after restart execute `jenkins_command` resource block or use `jenkins_plugin` block to install a plugin.

### Expected Result:
That plugin will install or jenkins will be available to do the commands that were passed to it.

### Actual Result:
the run fails because the jenkins service is not 'ready' but it is 'running'.
```
           ================================================================================
           Error executing action `install` on resource 'jenkins_plugin[antisamy-markup-formatter]'
           ================================================================================

           Errno::EHOSTUNREACH
           -------------------
           Failed to open TCP connection to localhost:8080 (No route to host - connect(2) for "localhost" port 8080)
```

**Comment by joshoohaah** [comment]
it should be noted I was able  to hack a workaround by putting a block to check if the jenkins homepage is returning a `200` (alive) message before going to the next step.

```
bash 'wait for Jenkins to get to ready State' do
  user 'root'
  code <<-EOH
  RUNNING=$(curl -Is http://localhost:#{node['jenkins']['port']} | grep HTTP | awk '{print $2}')
  until [ $RUNNING = 200 ]; do
  	echo $RUNNING
  	sleep 5
  	RUNNING=$(curl -Is http://localhost:#{node['jenkins']['port']} | grep HTTP | awk '{print $2}')
  done
  EOH
end

**Comment by coltrey** [comment]
The workaround I needed was to ensure that the API is ready to receive other commands:
```
  jenkins_command 'who-am-i' do
    retries 10
    retry_delay 30
  end

```

**Comment by espoelstra** [comment]
The cookbook should have automatic handling if you issue a `jenkins_command 'restart'` and it will not allow the cookbook/recipe to continue until it is back or throw an error if it never comes back. Both of the mentioned methods are pretty effective if you are restarting the system service for `jenkins`.

**Comment by djessich** [comment]
I do have the same problem, when installing a plugin using the `jenkins_plugin` resource from this cookbook. After each plugin installation Chef Client will notifiy `jenkins_command('safe-restart')` resource which safely restarts Jenkins. This fails because Chef Client will continue although Jenkins is not ready.

Any ideas when this problem will be solved in this cookbook?

**Comment by damacus** [comment]
Closing this issue as stale. It was opened in 2018 and the cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.
