### ISSUE TITLE
JenkinsWindowsSlave fails due to slave_jar_resource no longer defined in JenkinsJnlpSlave

### ISSUE THREAD

**Issue by timor-raiman** [sous-chefs/jenkins#670]
### Cookbook version
5.0.5

### Chef-client version
12.0.3

### Platform Details
windows 6.3.9600

### Scenario:
create windows jenkins slave

### Steps to Reproduce:
define a windows slave like so:
if platform_family?('windows')
    jenkins_home = "C:/jenkins_#{windows_user}"
    jenkins_user = "#{windows_domain}\\#{windows_user}"
    directory jenkins_home do
        owner jenkins_user
    end
    jenkins_windows_slave node.name do
        remote_fs       jenkins_home
        user            jenkins_user
        password        windows_password
        description     'Configured by chef'
        executors       1
        usage_mode      'exclusive'
        labels          options['labels_common'] + options['labels_more'] + automatic_labels
    end
end

### Expected Result:
jnlp windows slave created

### Actual Result:
chef run fails with exception:
 NameError
 ---------
 No resource, method, or local variable named `slave_jar_resource' for `Chef::Provider::JenkinsWindowsSlave ""'

**Comment by gscho** [comment]
Looks like the method was removed:
https://github.com/chef-cookbooks/jenkins/commit/71269fc5f37f267ca5af48f6fc21367510310b16#diff-63269eb765492a8a8fbb3d28b7cba084L208

I'm going to try defining the method inside of the libraries/slave_windows.rb file and see how that goes.

**Comment by skylerto** [comment]
@gscho there is already a PR for this #671

**Comment by tas50** [comment]
The fix for this issue has been released to Supermarket

**Comment by skylerto** [comment]
@tas50 thanks for merging this in! Does the release to public supermarket take awhile? v5.0.6 is 404'ing (https://supermarket.chef.io/cookbooks/jenkins/versions/5.0.6)

**Comment by tas50** [comment]
@skylerto Should be up there now

**Comment by skylerto** [comment]
thanks!

**Comment by damacus** [comment]
Closing this issue as stale. It was opened in 2018 and the cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.
