### ISSUE TITLE
Option to restart jenkins when openjdk package is updated

### ISSUE THREAD

**Issue by iancward** [sous-chefs/jenkins#678]
### Cookbook version
v5.0.3

### Chef-client version
12.14.89

### Platform Details
RHEL6

### Scenario:
I'm using both the `java` and `master` recipe (with package installation method). If the java/openjdk package is updated, jenkins doesn't really handle it well.

### Steps to Reproduce:
- Deploy Jenkins, using this cookbook's `java` recipe and the `master` recipe with the package install method
- Update java/openjdk package (might need to wait for an update to be available--that shouldn't take long :stuck_out_tongue:)
- Fully test jenkins
- Experience java issue (in our case, we were trying to edit a job in the console and got a missing file error)

### Expected Result:
- It would be nice to have a mechanism or means to have this cookbook restart jenkins when the java package is updated

### Actual Result:
- We encounter a java error

## Proposed Solution
I think if the conditionals [here](https://github.com/chef-cookbooks/jenkins/blob/master/recipes/java.rb#L38-L49) were moved inside of the resource, it would be relatively straightforward to set up a `subscribes` from the `master` role that bumps the jenkins service if the package is updated.

**Comment by bby-bishopclark** [comment]
If you're installing Jenkins and OpenJDK from packages, your best bet is probably a trigger package to cause that update in response to the new OpenJDK installation.  Then you're covered no matter how that update happens.

**Comment by damacus** [comment]
Closing this issue as stale. It was opened in 2018 and the cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.
