### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by joshskains** [sous-chefs/jenkins#680]
Is this project dead? I see a lot of unanswered Issues.

**Comment by espoelstra** [comment]
@joshskains I believe this project is maintained by sous-chefs which is a group of volunteers who try to maintain cookbooks that are useful to the community when they are popular and the original maintainers no longer have the time to keep up. That said, being volunteers they don't always have time to tackle all the issues in all the cookbooks that they keep an eye on, and many times it falls on the community to answer some of the questions or provide workarounds or submit pull requests for the more experienced "sous-chefs" to review. Typically the best place to find answers to usage questions is StackOverflow or the Chef Slack channels, for other issues it helps to have a reproducible test case.

**Comment by bby-bishopclark** [comment]
... and when you've done both?  Can we check for signs of life?

**Comment by acrewdson** [comment]
It feels like things are somewhat stalled around here. @tas50 Please let us know if there is anything the community can do to help. Thank you.
